---
title: "mlwdata"

subtitle: "Clean and annotate Blantyre health centre coordinates"

author: |
  | Peter MacPherson
  |
  | Liverpool School of Tropical Medicine, Liverpool, UK
  | Malawi-Liverpool-Wellcome Clinical Research Programme, Blantyre, Malawi
  |

date: | 
  | `r format(Sys.time(), "%B %d, %Y")`
  |
  | Table of Contents:
output: 
  html_document:
    theme: cosmo
    highlight: espresso
    toc: true
---

<br>

## 1. Backgound

This file will import coordinates of Blantyre MoH Health Centres, and prepare for later use.

<br>

## 2. Set-up

Load all required packages for analysis.

```{r setup, echo=FALSE, include=FALSE, message=FALSE, comment=NA, warning=FALSE}
library(tidyverse)    #for data manipulation
library(sf)
library(knitr)        #for tables
library(usethis)
library(here)

```

<br>

## 3. Import datasets

Import data required for the analysis.

```{r import}

clinics <- st_read(here::here("data-raw/02_blantyre_health_centres/BLANTYRE HEALTH CENTRES.kml"))

clinics <- clinics %>%
  dplyr::select(clinic = Name, -Description)

print(head(clinics))

clinics <- st_zm(clinics)
print(head(clinics))

blantyre_clinics <- clinics

use_data(blantyre_clinics, overwrite = TRUE)

```

<br>

<br>

## 4. Reproducibility

This reproduction of the analysis was run by: 

```{r sysinfo, echo=FALSE, message=FALSE, comment=NA, warning=FALSE}

sysinfo <- Sys.info()

sysinfo <- data.frame(keyName=names(sysinfo), value=sysinfo, row.names=NULL)

sysinfo %>% kable()
```

Analysis was run at **`r Sys.time()`**, and using the following Session Info:

```{r sessioninfo, echo=FALSE, results='markdown', message=FALSE, comment=NA, warning=FALSE}
sessionInfo()
```
